### ISSUE TITLE
Shutdown when 

### ISSUE THREAD

**Issue by hchu0701** [playframework/play-scala-starter-example#65]
Hi, I have trouble when I want to execute this sample

# steps
git clone https://github.com/playframework/play-scala-starter-example.git
cd play-scala-starter-example
sbt run

```
[info] Loading settings from plugins.sbt ...
[info] Loading project definition from /Users/myname/code/play-scala-starter-example/project
[info] Loading settings from build.sbt ...
[info] Set current project to play-scala-starter-example (in build file:/Users/myname/code/play-scala-starter-example/)

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by play.runsupport.classloader.DelegatingClassLoader (file:/Users/myname/.ivy2/cache/com.typesafe.play/run-support_2.12/jars/run-support_2.12-2.6.9.jar) to method java.lang.ClassLoader.findResource(java.lang.String)
WARNING: Please consider reporting this to the maintainers of play.runsupport.classloader.DelegatingClassLoader
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
--- (Running the application, auto-reloading is enabled) ---

[info] p.c.s.AkkaHttpServer - Listening for HTTP on /0:0:0:0:0:0:0:0:9000

(Server started, use Enter to stop and go back to the console...)
```

Then, It works when I curl http://localhost:9000 
But the server will be crashed when I connect with browser
```
Uncaught error from thread [play-dev-mode-akka.actor.default-dispatcher-9]: javax/xml/bind/DatatypeConverter, shutting down JVM since 'akka.jvm-exit-on-fatal-error' is enabled for for ActorSystem[play-dev-mode]
java.lang.NoClassDefFoundError: javax/xml/bind/DatatypeConverter
	at io.jsonwebtoken.impl.Base64Codec.decode(Base64Codec.java:26)
	at io.jsonwebtoken.impl.DefaultJwtBuilder.signWith(DefaultJwtBuilder.java:106)
	at play.api.mvc.JWTCookieDataCodec$JWTFormatter.format(Cookie.scala:718)
	at play.api.mvc.JWTCookieDataCodec.encode(Cookie.scala:577)
	at play.api.mvc.JWTCookieDataCodec.encode$(Cookie.scala:575)
	at play.api.mvc.DefaultJWTCookieDataCodec.encode(Cookie.scala:768)
	at play.api.mvc.FallbackCookieDataCodec.encode(Cookie.scala:742)
	at play.api.mvc.FallbackCookieDataCodec.encode$(Cookie.scala:741)
	at play.api.mvc.DefaultSessionCookieBaker.encode(Session.scala:95)
	at play.api.mvc.CookieBaker.encodeAsCookie(Cookie.scala:414)
	at play.api.mvc.CookieBaker.encodeAsCookie$(Cookie.scala:413)
	at play.api.mvc.DefaultSessionCookieBaker.encodeAsCookie(Session.scala:95)
	at play.api.mvc.Result.$anonfun$bakeCookies$2(Results.scala:297)
	at scala.Option.map(Option.scala:146)
	at play.api.mvc.Result.bakeCookies(Results.scala:296)
	at play.core.server.common.ServerResultUtils.prepareCookies(ServerResultUtils.scala:227)
	at play.core.server.AkkaHttpServer.$anonfun$executeAction$3(AkkaHttpServer.scala:303)
	at akka.http.scaladsl.util.FastFuture$.strictTransform$1(FastFuture.scala:41)
	at akka.http.scaladsl.util.FastFuture$.transformWith$extension1(FastFuture.scala:55)
	at akka.http.scaladsl.util.FastFuture$.flatMap$extension(FastFuture.scala:26)
	at play.core.server.AkkaHttpServer.executeAction(AkkaHttpServer.scala:302)
	at play.core.server.AkkaHttpServer.executeHandler(AkkaHttpServer.scala:255)
	at play.core.server.AkkaHttpServer.handleRequest(AkkaHttpServer.scala:201)
	at play.core.server.AkkaHttpServer.$anonfun$createServerBinding$1(AkkaHttpServer.scala:107)
	at akka.stream.impl.fusing.MapAsync$$anon$24.onPush(Ops.scala:1191)
	at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:512)
	at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:475)
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:371)
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:584)
	at akka.stream.impl.fusing.GraphInterpreterShell$AsyncInput.execute(ActorGraphInterpreter.scala:468)
	at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:559)
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:741)
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:756)
	at akka.actor.Actor.aroundReceive(Actor.scala:517)
	at akka.actor.Actor.aroundReceive$(Actor.scala:515)
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:666)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:527)
	at akka.actor.ActorCell.invoke(ActorCell.scala:496)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

# notes
```
$java -version
java version "9.0.1"
Java(TM) SE Runtime Environment (build 9.0.1+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.1+11, mixed mode)

$sbt about
[info] Loading settings from plugins.sbt ...
[info] Loading project definition from /Users/myname/code/play-scala-starter-example/project
[info] Loading settings from build.sbt ...
[info] Set current project to play-scala-starter-example (in build file:/Users/myname/code/play-scala-starter-example/)
[info] This is sbt 1.0.2
[info] The current project is {file:/Users/myname/code/play-scala-starter-example/}root 1.0-SNAPSHOT
[info] The current project is built against Scala 2.12.4
```

**Comment by marcospereira** [comment]
Hi @hchu0701,

That is because you are using Java 9, which requires additional JVM parameters. You can see https://github.com/playframework/playframework/issues/7879 for more details. Also, see this discussion on the mailing list:

https://groups.google.com/d/msg/play-framework/e3KLg94j5_M/yCr_yAGEAwAJ

I'm closing this issue but will reopen if needed.
